# Generated by Django 6.0.3 on 2026-03-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairecotisation',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participation',
            name='cotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='cotisations.cotisation'),
        ),
        migrations.AddField(
            model_name='participation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentairecotisation',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='cotisations.participation'),
        ),
        migrations.AddField(
            model_name='signalementcotisation',
            name='cotisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_detail', to='cotisations.cotisation'),
        ),
        migrations.AddField(
            model_name='signalementcotisation',
            name='signaleur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_emis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('cotisation', 'membre')},
        ),
        migrations.AlterUniqueTogether(
            name='signalementcotisation',
            unique_together={('cotisation', 'signaleur')},
        ),
    ]
