# Generated by Django 6.0.3 on 2026-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvee'), ('refusee', 'Refusee'), ('executee', 'Executee')], default='en_attente', max_length=20)),
                ('traitement_auto', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'demandes_remboursement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='QuickPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente paiement'), ('paye', 'Paye'), ('expire', 'Expire')], default='en_attente', max_length=20)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quickpay',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('cotisation', 'Cotisation'), ('quickpay', 'QuickPay'), ('remboursement', 'Remboursement'), ('verification', 'Verification niveau')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operateur', models.CharField(blank=True, choices=[('mixx', 'Mixx by Yas'), ('moov', 'Moov Money'), ('tmoney', 'T-Money')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succes'), ('failed', 'Echec'), ('refunded', 'Rembourse')], default='pending', max_length=20)),
                ('reference_paydunya', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
