# Generated by Django 6.0.3 on 2026-03-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderemboursement',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_remboursement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demanderemboursement',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remboursements_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickpay',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickpay_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickpay',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickpay_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickpay',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paiements.transaction'),
        ),
        migrations.AddField(
            model_name='demanderemboursement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_remboursement', to='paiements.transaction'),
        ),
    ]
