# Generated by Django 6.0.3 on 2026-03-19 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone_whatsapp', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('niveau', models.CharField(choices=[('basic', 'Basique'), ('verified', 'Verifie'), ('business', 'Business')], default='basic', max_length=20)),
                ('email_verifie', models.BooleanField(default=False)),
                ('whatsapp_verifie', models.BooleanField(default=False)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('tentatives_echec', models.IntegerField(default=0)),
                ('bloque_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('biometrie_activee', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TokenTentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=200)),
                ('type_token', models.CharField(default='inscription', max_length=20)),
                ('tentatives', models.IntegerField(default=0)),
                ('bloque_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'token_tentatives',
                'unique_together': {('identifiant', 'type_token')},
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=8)),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], default='email', max_length=10)),
                ('type_token', models.CharField(choices=[('inscription', 'Inscription'), ('reset_password', 'Reset mot de passe'), ('connexion_magique', 'Connexion magique'), ('changement_wa', 'Changement WhatsApp')], default='inscription', max_length=20)),
                ('utilise', models.BooleanField(default=False)),
                ('expire_le', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_tokens',
            },
        ),
    ]
