# Generated by Django 6.0.2 on 2026-03-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('nb_nouveaux_users', models.IntegerField(default=0)),
                ('nb_transactions', models.IntegerField(default=0)),
                ('volume_total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('revenus_kotizo', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('nb_cotisations_creees', models.IntegerField(default=0)),
                ('nb_quickpay', models.IntegerField(default=0)),
                ('nb_alertes_fraude', models.IntegerField(default=0)),
                ('nb_tickets_ouverts', models.IntegerField(default=0)),
                ('nb_verifications_soumises', models.IntegerField(default=0)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rapports_journaliers',
                'ordering': ['-date'],
            },
        ),
    ]
