# Generated by Django 6.0.3 on 2026-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('plateforme', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('paiement', 'Paiement'), ('rappel', 'Rappel'), ('systeme', 'Systeme'), ('recu', 'Recu'), ('commentaire', 'Commentaire')], max_length=20)),
                ('canal', models.CharField(choices=[('inapp', 'In-App'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('push', 'Push')], default='inapp', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('envoye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
